### PR TITLE
Display cangjie code on wildcard usage (cangjie only)

### PR DESCRIPTION
**Pull request by NCHL**
Hi guys,

This is in response to issue #8 (helping users learn Cangjie by displaying the full code on wildcard usage). I implemented the first way suggested there and hope it would be useful for fellow cangjie learners. 

Cheers

### CODE REVIEW

**Comment by bochecha** [comment]
Hi, thanks for this pull request!

Unfortunately, as you can see the CI is currently broken.

It's not due to code you changed, or even code we changed in master (it's probably just Travis using an old Ubuntu), but we need to fix it before we can merge your code. I'll try and allocate time to do that ASAP.

---

About your code itself, we had worries that implementing it this way might be very distracting. (as said in #8). Did you try running ibus-cangjie with this patch applied? Was it distracting?

Maybe we should hide it by default, and have an option to enable it?

**Comment by NCHL** [comment]
Hi bochecha: 

Thank you for your comment! I'm excited to be a part of this.
Re. your question, personally I don't feel distracting (i3-gnome/arch), although obviously it will vary for different people and across environments. The "long code" is only displayed when * is used and when the input method is cangjie. Over time, if the common codes are memorized then those distractions will appear less often.

I agree that the better way is to turn this off by default with an option to enable it. The only thing I worry is that it would be too intrusive in one commit, and that's why I create a branch to test this feature first and see what you guys think! :)

**Comment by bochecha** [comment]
> The only thing I worry is that it would be too intrusive in one commit, and that's why I create a branch to test this feature first and see what you guys think! :)

Maybe then a commit to add the feature (as you did), then a second commit to add an option to the UI and have it disabled by default.

But take your time though, as I mentioned we need to fix the CI first, so don't rush. :-)

**Comment by NCHL** [comment]
> Maybe then a commit to add the feature (as you did), then a second commit to add an option to the UI and have it disabled by default.

Sounds good!

**Comment by mbridon** [comment]
Hi @NCHL.

It's been a long time, and lots happened since then, but basically we moved away from Github and are now hosted on gitlab.freedesktop.org/cangjie/ibus-cangjie

We're in the process of fainally merging your PR there, so I wanted to let you know that even if it seemed like we had forgotten after so long, we didn't. :grin: 

Your contribution was good, we still want it but life got in the way and made me lose 2-3 years back in 2020. :cry: 

I'm now slowly getting back to doing shit, and that included your PR which I rebased: https://gitlab.freedesktop.org/cangjie/ibus-cangjie/-/merge_requests/134

Once Koala reviews it, it will be merged and released as part of ibus-cangjie 2.5 :smile: 

Thank you very much for your contribution and your patience, my apologies for disappearing fr 2+ years. :+1:

**Pull request closed without merging**
